POST http://localhost:3000/users
Content-Type: application/json

{
  "username" : "whas",
  "pwd":"1234",
  "ime":"Marcus",
  "prezime": "Aurelius",
  "email":"ekke@gmail.com",
  "uloga": "ugostitelj"
}